add the ability to switch devices on a whim

diff --git a/bin/setwebcam b/bin/setwebcam
--- a/bin/setwebcam
+++ b/bin/setwebcam
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 
+set -Eeuo pipefail #fail fast
+
 # Setup
 CWD="$(pwd -P)"
 SCRIPTSDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
+
+trap error_cleanup ERR
 
 # functions
 cmsg() { # Output messages in color! :-)
@@ -53,26 +57,43 @@ cmsg() { # Output messages in color! :-)
     return 0
 }
 
+error_cleanup() {
+    trap - ERR
+    cmsg
+    cmsg -r "setwebcam failed..."
+    cmsg "Here's the list of webcam devices."
+    v4l2-ctl --list-devices
+}
+
+# default device number
+
+re='^[0-9]+$'
+device="${1:-0}"
+if [[ "${device}" =~ "$re" ]]; then
+   device="0"
+fi
 
 # start script
 
-cmsg -c "Setting webcam settings"
+cmsg -c "Setting webcam settings for device /dev/video${device}"
 
 # settings
-v4l2-ctl -d /dev/video4 --set-ctrl brightness=145
-v4l2-ctl -d /dev/video4 --set-ctrl contrast=30
-v4l2-ctl -d /dev/video4 --set-ctrl saturation=45
-v4l2-ctl -d /dev/video4 --set-ctrl hue=400
-v4l2-ctl -d /dev/video4 --set-ctrl white_balance_temperature_auto=1
-v4l2-ctl -d /dev/video4 --set-ctrl power_line_frequency=2
-#v4l2-ctl -d /dev/video4 --set-ctrl white_balance_temperature=5400
-v4l2-ctl -d /dev/video4 --set-ctrl sharpness=30
-v4l2-ctl -d /dev/video4 --set-ctrl backlight_compensation=62
-v4l2-ctl -d /dev/video4 --set-ctrl exposure_auto=3
-#v4l2-ctl -d /dev/video4 --set-ctrl exposure_absolute=5467
+v4l2-ctl -d "${device}" --set-ctrl brightness=145
+v4l2-ctl -d "${device}" --set-ctrl contrast=30
+v4l2-ctl -d "${device}" --set-ctrl saturation=45
+v4l2-ctl -d "${device}" --set-ctrl hue=400
+v4l2-ctl -d "${device}" --set-ctrl white_balance_temperature_auto=1
+v4l2-ctl -d "${device}" --set-ctrl power_line_frequency=2
+#v4l2-ctl -d "${device}" --set-ctrl white_balance_temperature=5400
+v4l2-ctl -d "${device}" --set-ctrl sharpness=40
+v4l2-ctl -d "${device}" --set-ctrl backlight_compensation=62
+v4l2-ctl -d "${device}" --set-ctrl exposure_auto=3
+#v4l2-ctl -d "${device}" --set-ctrl exposure_absolute=5467
 
 # focus controls
-v4l2-ctl -d /dev/video4 --set-ctrl focus_auto=0
-v4l2-ctl -d /dev/video4 --set-ctrl focus_absolute=175
+v4l2-ctl -d "${device}" --set-ctrl focus_auto=0
+v4l2-ctl -d "${device}" --set-ctrl focus_absolute=155
 
 cmsg -c "Done!"
+
+exit 0
